modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="stonercraft"
version="1.0.0"
displayName="StonerCraft"
description="""Grow, dry, and smoke — Stonercraft brings green life to Minecraft. Discover new plants, cultivate them on your farm, carefully dry your harvest, and enjoy a whole new chill gameplay loop inspired by laid-back stoner culture."""

[[dependencies.stonercraft]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.stonercraft]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
